### ISSUE TITLE
Download evaluations gets old version of eva sheet

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#74]
To cause to happen:

- grade some groups
- download evaluations
- grade some more groups
- download evaluations

might be a browser file caching issue?

**Comment by bmyerz** [comment]
Does this only reproduce on the apache server? @bellqueen not able to reproduce on local server

**Comment by bmyerz** [comment]
When logging in again on incognito tab, I was able to download the latest version of the file.

**Comment by bmyerz** [comment]
I think this would be best fixed by circumventing any file caching. Do this by always appending the current timestamp to the name of the file. For example, if we used datetime.now()...
all.xlsx becomes
all-2020-02-12 13:36:19.526562

This is what grading sites like ICON seem to do.

**Comment by JackyBreak** [comment]
In the template, I added a new argument which has current time in it, such that each time user click the download button, current time will be passed to the back-end function, the back-end function then will create a file has the current time in its name. By setting unique name to every download file, the issue is fixed.
